variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - target/

stages:
  - sanity
  - test
  - package

before_script:
  - rustc --version
  - cargo --version

sanity:
  image: rustlang/rust:nightly
  stage: sanity
  script: .ci/check_sanity.sh

test:
  image: rustlang/rust:nightly
  stage: test
  # Some of the mgmtd tests use an sqlite file in the same location and can only be run sequentially
  script: cargo test -- --test-threads=1

package:
  image: rustlang/rust:nightly
  stage: package
  when: manual
  artifacts:
    expire_in: 1 day
    name: "beegfs_rust_packages"
    paths:
      - packages
  script: .ci/generate_packages.sh
