accepted = ["MIT", "Apache-2.0", "ISC", "BSD-3-Clause", "Unicode-DFS-2016", "OpenSSL"]
workarounds = ["ring"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]
private = { ignore = true }
