[workspace]
members = ["shared", "mgmtd", "ctl", "config", "hsieh"]

[workspace.dependencies]
anyhow = "~1"
async-trait = "~0"
bytes = "~1"
clap = { version = "~4", features = ["derive"] }
env_logger = "~0"
itertools = "~0"
log = { version = "~0", features = ["std"] }
rusqlite = "~0"
serde = "~1"
serde_json = "~1"
thiserror = "~1"
tokio = { version = "~1", features = ["rt", "sync", "macros"] }
