[workspace]
resolver = "2"
members = ["shared", "mgmtd", "sqlite", "sqlite_check", "bee_serde_derive"]

[workspace.package]
edition = "2024"
authors = ["ThinkParQ GmbH"]
homepage = "https://www.beegfs.io"
documentation = "https://doc.beegfs.io"
publish = false

[workspace.dependencies]
anyhow = "1"
bytes = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0"
itertools = "0"
libc = "0"
log = { version = "0", features = ["std"] }
prost = "0"
protobuf = { git = "https://github.com/thinkparq/protobuf", rev = "4957cbcada125b549674bc9f98d9777052fb5c34" }
regex = "1"
ring = "0"
rusqlite = { version = "0", features = ["bundled", "vtab", "array"] }
serde = "1"
thiserror = "~2"
tokio = { version = "1", features = ["rt", "sync", "macros"] }
tokio-stream = { version = "0" }
tonic = { version = "0", features = ["tls"] }
uuid = { version = "1", features = ["v4"] }
