[workspace]
resolver = "2"
members = ["shared", "mgmtd"]

[workspace.dependencies]
anyhow = "~1"
async-trait = "~0"
bytes = "~1"
clap = { version = "~4", features = ["derive"] }
env_logger = "~0"
itertools = "~0"
log = { version = "~0", features = ["std"] }
prost = "~0"
rusqlite = "~0"
serde = "~1"
thiserror = "~1"
tokio = { version = "~1", features = ["rt", "sync", "macros"] }
tonic = "~0"
