# BeeGFS management runtime configuration
#
# THIS IS A TEMPORARY REPLACEMENT FOR THE NEW CTL AND WILL GO AWAY
#
# The configuration specified here is supposed to be done at runtime via the new ctl tool
# later on. While it is not yet fully implemented, this file can be used apply do all the
# configuration at managment start.
#
# Since the actual configuration is stored in the database, the changes made from this file are
# persistent. It doesn't need to be loaded every time.

registration_enable = true

node_offline_timeout = "180s"
client_auto_remove_timeout = "30m"

quota_enable = false
quota_user_ids = []
quota_group_ids = []
quota_update_interval = "30s"

[cap_pool_meta_limits]
inodes_low = "10M"
inodes_emergency = "1M"
space_low = "10GiB"
space_emergency = "3GiB"

# Uncommenting enables dynamic meta capacity pools
# [cap_pool_dynamic_meta_limits]
# inodes_normal_threshold = "10M"
# inodes_low_threshold = "1M"
# space_normal_threshold = "10GiB"
# space_low_threshold = "3GiB"
# inodes_low = "20M"
# inodes_emergency = "2M"
# space_low = "20GiB"
# space_emergency = "6GiB"

[cap_pool_storage_limits]
inodes_low = "10M"
inodes_emergency = "1M"
space_low = "512GiB"
space_emergency = "10GiB"

# Uncommenting enables dynamic storage capacity pools
# [cap_pool_dynamic_storage_limits]
# inodes_normal_threshold = "10M"
# inodes_low_threshold = "1M"
# space_normal_threshold = "512GiB"
# space_low_threshold = "10GiB"
# inodes_low = "20M"
# inodes_emergency = "2M"
# space_low = "1024GiB"
# space_emergency = "20GiB"
