# BeeGFS management configuration file
#
# This file configures the BeeGFS management node and can be used as an alternative or together with
# command line arguments. Arguments given to the CLI overwrite arguments specified here,
# arguments specified here overwrite the defaults.
# 
# The command line help might have more information on a specific setting. Run the management
# binary with `--help` to display it.



### Connection and storage ###

# TCP/UDP port to listen for incoming connections / messages using the old BeeMsg protocol
# beemsg-port = 8008

# TCP port for the gRPC server to listen on
# grpc-port = 8010

# Disables TLS for gRPC communication
# tls-disable = false

# The PEM encoded .X509 certificate file that provides the identity of the gRPC server
# tls-cert-file = /etc/beegfs/cert.pem

# The private key file belonging to the above certificate
# tls-key-file = /etc/beegfs/key.pem

# Network interfaces reported to other nodes. 
# interfaces = ["eth0", "eth1"]

# Maximum number of outgoing connections per node
# connection-limit = 12

# Disable authentication
# auth-disable = false

# Location of the file containing the authentication secret
# auth-file = "/etc/beegfs/conn.auth"

# Location of the SQLite database file
# db-file = "/var/lib/beegfs/mgmtd.sqlite"

# Log target to use
# log-target = "journald"

# Log level to use (valid are "error", "warn", "info", "debug", "trace")
# log-level = "warn"


### Generic ###

# Disallows registration of new nodes and targets
# registration-disable = false

# The time after server nodes that send no updates are considered offline.
# node-offline-timeout = "180s"

# The time after client nodes that send no updates are considered offline and removed from client
# list.
# client-auto-remove-timeout = "30m"



### Quota ###

# Enables quota data collection and checks. Allows querying the state and setting limits (which do
# nothing without enforcement being enabled). Causes higher system load.
# quota-enable = false

# Enables quota enforcement, meaning that the exceeded IDs are calculated and pushed to the servers
# on a regular basis.Requires quota_enable = true. Causes higher system load.
# quota-enforce = false

# Update interval of quota information. Defines how often the management pulls the quota information
# from all storage nodes, calculates the IDs that exceed the limits and reports them back to the
# server nodes.
# quota-update_interval = "30s"

# The following options specify the User/Group IDs to be fetched from storage services for quota
# checking and enforcement. They are disabled by default and least one needs to be enabled for
# quota enforcement having any effect. They can be mixed.

# Use the local systems user IDs for the quota check, starting with the given ID.
# quota-user-system-ids-min = 1000

# File containing numeric user IDs to be used for the quota check. The file must only
# contain numeric IDs separated by whitespaces.
# quota-user-ids-file = ""

# Range of user IDs to be used for the quota check.
# quota-user-ids-range-start = 1000
# quota-user-ids-range-end = 1000

# Same as above, but for group IDs

# quota-group-system-ids-min = 1000
# quota-group-ids-file = ""
# quota-group-ids-range-start = 1000
# quota-group-ids-range-end = 1000


### Capacity pools ### 

# Sets the limits / boundaries of the meta capacity pools
# [cap-pool-meta-limits]
# inodes-low = "10M"
# inodes-emergency = "1M"
# space-low = "10GiB"
# space-emergency = "3GiB"

# Sets the limits / boundaries of the dynamic meta capacity pools and the thresholds that determine
# which limits shall be used.
# [cap-pool-dynamic-meta-limits]
# inodes-normal-threshold = "10M"
# inodes-low-threshold = "1M"
# space-normal-threshold = "10GiB"
# space-low-threshold = "3GiB"
# inodes-low = "20M"
# inodes-emergency = "2M"
# space-low = "20GiB"
# space-emergency = "6GiB"

# Sets the limits / boundaries of the storage capacity pools
# [cap-pool-storage-limits]
# inodes-low = "10M"
# inodes-emergency = "1M"
# space-low = "512GiB"
# space-emergency = "10GiB"

# Sets the limits / boundaries of the dynamic storage capacity pools and the thresholds that determine
# which limits shall be used.
# [cap-pool-dynamic-storage-limits]
# inodes-normal-threshold = "10M"
# inodes-low-threshold = "1M"
# space-normal-threshold = "512GiB"
# space-low-threshold = "10GiB"
# inodes-low = "20M"
# inodes-emergency = "2M"
# space-low = "1024GiB"
# space-emergency = "20GiB"
