name: Check
run-name: Check ${{ github.ref_name }} by @${{ github.actor }}
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  workflow_call:
env:
  # Cargo must use git cli for checkouts instead of builtin functionality to respect the repla
  CARGO_NET_GIT_FETCH_WITH_CLI: true
jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CARGO_LOCKED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1
        with:
          components: clippy
          bins: cargo-deny
      - name: Setup nightly toolchain and tools
        run: |
          rustup toolchain install nightly
          rustup component add --toolchain nightly rustfmt
      - name: Checks
        run: make check
      - name: Run tests
        run: make test
      - name: License and compliance
        run: make deny
