name: Build packages

# Currently broken

on: [workflow_dispatch]

env:
  # Cargo must use git cli for checkouts instead of builtin functionality to respect the repla
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  package:
    needs: [checks]
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          # We use the musl libc implementation (https://musl.libc.org/) which is statically linked into
          # the binary
          apt-get update && apt-get -y install musl-tools
          rustup target add x86_64-unknown-linux-musl

          # cargo tools tp generate packages
          cargo install cargo-generate-rpm
          cargo install cargo-deb
      - name: Build
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl
          strip -s target/x86_64-unknown-linux-musl/release/mgmtd
      - name: Generate packages
        run: |
          mkdir -p packages
          rm -rf packages/*
          cargo deb -p mgmtd --target=x86_64-unknown-linux-musl -o packages
          cargo generate-rpm -p mgmtd --target=x86_64-unknown-linux-musl --auto-req=disabled -o packages          
      - name: Upload packages artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages_${{ github.sha }}_${{ github.run_number }}
          path: packages/
