name: Build Package Workflow

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: self-hosted
    container: 
      image: rustlang/rust:nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Rust version
        run: rustc --version
      - name: Check Cargo version
        run: cargo --version
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Build Package
        run: .ci/generate_packages.sh
      - name: Upload packages artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages_${{ github.sha }}_${{ github.run_number }}
          path: packages/
