name: Build Packages

# Currently broken

on: [workflow_dispatch]

env:
  # Cargo must use git cli for checkouts instead of builtin functionality to respect the repla
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git
        run: git config --global url."https://${{ secrets.CI_PROTOBUF_ACCESS }}@github.com/thinkparq/protobuf".insteadOf https://github.com/thinkparq/protobuf
      - name: Cargo deny
        run: |
          cargo install cargo-deny
          cargo deny check
      - name: Install tools
        run: |
          apt-get update && apt-get -y install musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo install --root . cargo-generate-rpm cargo-deb
      - name: Build
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl
          strip -s target/x86_64-unknown-linux-musl/release/mgmtd
      - name: Generate packages
        run: |
          mkdir -p packages
          rm -rf packages/*
          bin/cargo-deb -p mgmtd --target=x86_64-unknown-linux-musl -o packages
          bin/cargo-generate-rpm -p mgmtd --target=x86_64-unknown-linux-musl -o packages
      - name: Upload packages artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages_${{ github.sha }}_${{ github.run_number }}
          path: packages/
