name: Create release
run-name: Create release for ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
  push:
    # This should run automatically on pushing a BeeGFS version tag, but not on any others
    tags:
      - "v*.*.*"
env:
  # Cargo must use git cli for checkouts instead of builtin functionality to respect the repla
  CARGO_NET_GIT_FETCH_WITH_CLI: true
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_LOCKED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Important to fetch the tags
          fetch-depth: 0
      - name: Build Packages
        uses: ./.github/actions/package
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PUBLICREPO_GPGPACKAGEKEY }}
          passphrase: ${{ secrets.PUBLICREPO_GPGPACKAGEPASSPHRASE }}
      - name: Sign checksums file
        run: |
          cd target/package
          export GPG_TTY=$(tty)
          gpg --pinentry-mode loopback --passphrase ${{ secrets.PUBLICREPO_GPGPACKAGEPASSPHRASE }} --trust-model always --detach-sign -o checksums.txt.sig -r packages@beegfs.com checksums.txt
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/package/*.deb,target/package/*.rpm,target/package/checksums*"
          allowUpdates: true
          updateOnlyUnreleased: true
          removeArtifacts: true
          generateReleaseNotes: true
          draft: false
